### ISSUE TITLE
请问下我需要做什么才能使用该项目

### ISSUE THREAD

**Issue by qlgd** [purofle/mdt-bt#1]
我希望可以在我的服务器群内添加具有蓝图解析的机器人但是我并不会使用您的这个项目，如果您有时间稍微指点一下我我会非常感谢您的

**Comment by purofle** [comment]
好，我在近期会写README.


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年4月6日(周二) 下午5:04
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [purofle/mdt-bt] 请问下我需要做什么才能使用该项目 (#1)




 
我希望可以在我的服务器群内添加具有蓝图解析的机器人但是我并不会使用您的这个项目，如果您有时间稍微指点一下我我会非常感谢您的
 
&mdash;

**Comment by qlgd** [comment]
> 好，我在近期会写README。
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2021年4月6日(周二) 下午5:04 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [purofle/mdt-bt] 请问下我需要做什么才能使用该项目 (#1) 我希望可以在我的服务器群内添加具有蓝图解析的机器人但是我并不会使用您的这个项目，如果您有时间稍微指点一下我我会非常感谢您的 &mdash; You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

好的，谢谢您
